### ISSUE TITLE
HOME test failures on Windows

### ISSUE THREAD

**Issue by Playacem** [cdimascio/dotenv-kotlin#10]
I just made a fresh fork of java-dotenv and after cloning my fork and running `mvn test` i receive a lot of test failures. The error is always the same.

```
[ERROR] Failures:
[ERROR]   DotEnvDslTest.dotenvIgnoreMalformed:34 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvDslTest.dotenvIgnoreMissing:91 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvDslTest.resourceCurrent:72 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvDslTest.resourceFilename:60 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvDslTest.resourceRelative:47 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvTest.dotenvFilename:57 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvTest.dotenvIgnoreMalformed:38 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvTest.dotenvIgnoreMissing:101 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvTest.resourceCurrent:82 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[ERROR]   DotEnvTest.resourceRelative:70 expected:<C:\Users\adm[]> but was:<C:\Users\adm[\]>
[INFO]
[ERROR] Tests run: 14, Failures: 10, Errors: 0, Skipped: 0
```

In my real world project I fixed ~this~ [issue #11] by specifying the directory as `"."`:
`Dotenv.configure().directory(".").ignoreIfMissing().load();`

**Comment by Playacem** [comment]
The fix I describe is actually a different Windows issue where java-dotenv cant find a .env file in the current working directory without the explicit config.

Edit: opened a new issue for the default config issue, see #11

**Comment by Playacem** [comment]
I have an environment variable called HOME with the value `C:\Users\adm\`.
I found [this StackOverflow question](https://stackoverflow.com/questions/585534/what-is-the-best-way-to-find-the-users-home-directory-in-java) which references this [JDK bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4787931) but that bug is supposedly fixed in Java 8.

My Java version:
```
λ  java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)
```

edit:
According to [this answer](https://superuser.com/a/607110) `HOME` is not set on a fresh windows system. So we might have to change the test approach

**Comment by cdimascio** [comment]
@Playacem thanks so much for trying out the build on Windows.
I've created a branch which i 'think' should resolve the test errors. would appreciate it if you can give it a try. have a look at the `windows-fixes` branch

i also delivered a small change to update the default path, which i presume will solve the issues you saw on windows

The PR is here: https://github.com/cdimascio/java-dotenv/pull/12

**Comment by Playacem** [comment]
I just tested the changes and the test errors are now resolved.

**Comment by cdimascio** [comment]
@Playacem Thank you for verifying. i'll merge this to master
