### ISSUE TITLE
DotenvReader logic is flawed

### ISSUE THREAD

**Issue by Playacem** [cdimascio/dotenv-kotlin#13]
While debugging issue #11 I found some interesting behaviour in the following tests:

- DotEnvTest#dotenvMissing
- DotEnvTest#dotenvIgnoreMissing
- DotEnvDslTest#dotenvMissing
- DotEnvDslTest#dotenvIgnoreMissing

I added the following line to the DotEnvReader: `println("[dotenv] location: $location")`, which results in the following output for all the above tests: `[dotenv] location: /missing//.env`

All tests have setting the directory with the value `/missing/.env` in common.
I guess we need to swap the order of operations to remove the duplicate slash.
The current solution would reduce the following valid path `/missing/.env/` to the wrong `/missing/`

**Comment by cdimascio** [comment]
@Playacem thanks again. you nailed it. making that fix now

**Comment by cdimascio** [comment]
This is now fixed on master. I've created a new version 3.1.6. It will take a day or so before its live on Maven Central

If you can't wait, you can do the following to pull immediately from JCenter:

**Gradle**

```groovy
repositories {
    maven {
        url  "https://dl.bintray.com/cdimascio/maven" 
    }
}
```

or 

**Maven Settings**

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd'
          xmlns='http://maven.apache.org/SETTINGS/1.0.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    
    <profiles>
        <profile>
            <repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-cdimascio-maven</id>
                    <name>bintray</name>
                    <url>https://dl.bintray.com/cdimascio/maven</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-cdimascio-maven</id>
                    <name>bintray-plugins</name>
                    <url>https://dl.bintray.com/cdimascio/maven</url>
                </pluginRepository>
            </pluginRepositories>
            <id>bintray</id>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>bintray</activeProfile>
    </activeProfiles>
</settings>
```
