### ISSUE TITLE
Not working correctly when I execute a jar after gradle build

### ISSUE THREAD

**Issue by aslllllo** [cdimascio/dotenv-kotlin#26]
Hello, I am building  a spring boot application with java-dotenv.

The  .env is under "src/main/resources" folder and the application works perfectly when I start the application in my IDE(Intellj Idea).

A jar file is created by gradle when I build the project and I will get the following errors if I execute the jar file directly.

` Suppressed: io.github.cdimascio.dotenv.DotEnvException: Could not find .\.env on the file system `

I have read [this project](https://github.com/cdimascio/kotlin-spring-mvc-template) for reference and the project I created is similar to the kotlin-spring-mvc-template.

Not sure what was wrong. I would appreciate if you would give me some help.

**Comment by cdimascio** [comment]
@aslllllo is the .env present in your jar file? and if so where is it located?

**Comment by cdimascio** [comment]
@aslllllo any update?
