### ISSUE TITLE
Directory configuration not working correctly

### ISSUE THREAD

**Issue by jessevdp** [cdimascio/dotenv-kotlin#3]
OS: MacOS v10.13.4
Java version: JavaSE-1.8
Dotenv version: 3.1.0

---

When configuring the directory `Dotenv` uses it seems to make a difference weather or not you use a dot in the path.

The following code works just fine:
```java
Dotenv env = Dotenv.configure().directory("./").load();
```

However this code throws an error:
```java
Dotenv env = Dotenv.configure().directory("/").load();
```
```
Exception in thread "main" io.github.cdimascio.dotenv.DotEnvException: Could not find /.env on the classpath
	at io.github.cdimascio.dotenv.internal.ClasspathHelper.loadFileFromClasspath(ClassPathHelper.kt:28)
	at io.github.cdimascio.dotenv.internal.DotenvReader.read(DotenvReader.kt:26)
	at io.github.cdimascio.dotenv.internal.DotenvParser.parse(DotenvParser.kt:18)
	at io.github.cdimascio.dotenv.DotenvBuilder.load(Dotenv.kt:48)
	at dotenv_test.Main.main(Main.java:9)
```

Removing the configuration entirely should according to the documentation load the `dotenv` file from the root of the project: `./` however this throws an error too. Which seems especially weird to me.

**Comment by cdimascio** [comment]
@jessevdp, this is the correct behavior. The two paths are different locations. 
The first, `./` is a relative path, thus `Dotenv` will search with respect to the current working directory
The second, `/` is an absolute path, thus `Dotenv` will search the root of your filesystem for `.env`

Note if there are no matches, `Dotenv` will then search the java classpath. It's common that this be the `resources` directory particularly if you're using the maven project structure

**Comment by cdimascio** [comment]
@jessevdp this stuff gets a bit tricky, but ultimately, you need to know the directory from which `java` is executed from. It determines the point from which relative paths are resolved e.g. `./`

You're IDE may also set this directory. If possible, it may be worth executing your app from the command line to be absolutely sure which directory you are running from

Let me know if i can help in anyway, I definitely want to get this working for you

**Comment by cdimascio** [comment]
These examples may help

**Spring**: `.env` is pulled from the classpath. It is stored in `resources` directory:
https://github.com/cdimascio/kotlin-swagger-spring-functional-template/tree/master/src/main/resources

There is an Android example in the README as well, if needed

**Comment by jessevdp** [comment]
I am using maven. I did just try to make a `resource` directory and put the `.env` file in there and I removed all the configuration. This still gave me the same error.

I am using Eclipse so there's a slight chance that just adding the folder didn't have the desired effect. I know there's a `.classpath` file. I'm just not very used to what it does or how to use it. By default it's excluded from source control as well.

I come from the world of `Node.js` where everyone has to compile and execute their apps from the command line. These concepts are kind of foreign to me.

---

>https://github.com/cdimascio/kotlin-swagger-spring-functional-template/tree/master/src/main/resources`

That link is broken, should remove the back-tick. 

>The first, ./ is a relative path, thus Dotenv will search with respect to the current working directory
The second, / is an absolute path, thus Dotenv will search the root of your filesystem for .env.

Oeps, that's true. Guess it was in too having a bit of tunnel vision yesterday 😂

**Comment by cdimascio** [comment]
@jessevdp here is a super basic example of a Maven project using dotenv where `.env` lives in the the `resources` directory

https://github.com/cdimascio/java-dotenv-example

Be sure to set up the directory structure as shown in this example. It aligns with the standard Maven structure.

The example has instructions to run on the command line. Once, you see that work, try from eclipse

**Comment by cdimascio** [comment]
Here is a direct link to the actual code (you'll find it is very simple):

https://github.com/cdimascio/java-dotenv-example/blob/master/src/main/java/io/github/cdimascio/examples/dotenv/Main.java

And a link to the `.env` file
https://github.com/cdimascio/java-dotenv-example/blob/master/src/main/resources/.env

And the `pom.xml` file
https://github.com/cdimascio/java-dotenv-example/blob/master/pom.xml

Again, the project is set up using the Maven structure. Assuming you set your project up similarly (which is recommended even if not using `java-dotenv`), it should work

**Comment by jessevdp** [comment]
Ahh I see. That's totally fixed. I included the `resources` folder under `src/main` instead of in the root of the project.

**Comment by cdimascio** [comment]
Excellent!  I added the example to the `README`. closing this out
