### ISSUE TITLE
5.1.3 library version does not resolve correctly .env file location in jar file.

### ISSUE THREAD

**Issue by Michal-SG** [cdimascio/dotenv-kotlin#38]
Steps to reproduce:  

- checkout project: https://github.com/cdimascio/kotlin-spring-mvc-template
- replace 3.1.3 library version with 5.1.3
- create `.env` file under `src/main/resources`
- verify that running `gradle bootRun` command resolves .env file location correctly.
![image](https://user-images.githubusercontent.com/53607028/76312676-d8043f80-62d3-11ea-8ea6-2bf9148babd8.png)

- verify that running `gradle bootJar && java -jar build/libs/example-service-1.0.0.jar` doesn't resolve `.env` files location properly
![image](https://user-images.githubusercontent.com/53607028/76312747-f833fe80-62d3-11ea-948f-421a232aff03.png)

Tested also with 3.1.3 version and it was working correctly back then. 

Update:
Last **working** version: 3.1.4
First **not working** version: 3.1.5

**Comment by Michal-SG** [comment]
Haven't spotted difference in jar structure. In both cases (3.1.3 & 5.1.3) `.env` file is located in `BOOT-INF/classes` directory

**Comment by cdimascio** [comment]
@Michal-SG Thanks for the issue. I published a new version, `5.1.4` with the fix. 

Note, it can sometimes take 24 hours for the jar to propagate to mavencentral. that being said, it should be available on jcenter now

Let me know how it goes

**Comment by Michal-SG** [comment]
Thanks @cdimascio for quick action. Today verified issue with newest library version and it seems to not be the case anymore. Dziekuje!
