### ISSUE TITLE
Support when no .env file is present

### ISSUE THREAD

**Issue by jessevdp** [cdimascio/dotenv-kotlin#4]
Currently `Dotenv` will throw an error if it is loaded when no `.env` file is present in the project. This causes a couple of problems especially when dealing with CI.

It is advised to not include the `.env` file in source control, this means there will be no `.env` file present when a service like [Travis CI](https://about.travis-ci.org) downloads the repository for testing. A service like Travis CI does export plenty of environment variables that can be used. Besides that CI services offer ways to export custom environment variables.

However it would be weird to have to switch between methods of retrieving environment variables just because you don't have the file. **Just because there is no `.env` file present doesn't mean that there are no environment variables that are needed.**

Perhaps a warning would be in order. Perhaps including an error for `env` variables that are not specified. (Note that leaving a variable might be different from not including one. A password can be blank for instance.)

**Comment by cdimascio** [comment]
@jessevdp you can use `ignoreIfMissing` to request that `Dotenv` not throw when `.env` is missing. Have you tried that option?

Java
```java
Dotenv dotenv = Dotenv.configure()
        .ignoreIfMissing()
        .load();
```

or with Kotlin
```kotlin
val dotenv = dotenv {
    ignoreIfMissing = true
}
```

with `ignoreIfMissing`, you can continue to call `dotenv.get("MY_EV")`, despite there being no `.env` file. Dotenv will continue to passthrough to `System.getenv()`, hence you'll still have access to all the EVs set in your environment. `Dotenv` always prioritizes the actual env var over what is in `.env`

**Comment by cdimascio** [comment]
Closing this one out as the functionality you are looking for does exist. Please reopen if you disagree

**Comment by jessevdp** [comment]
👍
