### ISSUE TITLE
Make dotenv env variables available in System.getProperty() too

### ISSUE THREAD

**Issue by srnagar** [cdimascio/dotenv-kotlin#40]
>Q: Why should I use dotenv.get(“MY_ENV_VAR”) instead of System.getenv(“MY_ENV_VAR”)
A: Since Java does not provide a way to set environment variables on a currently running process, vars listed in .env cannot be set and thus cannot be retrieved using System.getenv(…).

Given that `System.getenv("MY_ENV_VAR")` doesn't allow adding new environment variables at runtime, the other option is to plug the dotenv configured variables into `System.setProperty()`. 

This will allow libraries to use either `System.getProperty("MY_ENV_VAR")` or `dotenv.get("MY_ENV_VAR")`. 

A simple change would look like this after Dotenv is created.

```java
Dotenv
   .load()
   .entries()
   .filter(entry -> System.getProperty(entry.getKey) == null)
   .forEach(entry -> System.setProperty(entry.getKey(), entry.getValue()));
```

**Comment by cdimascio** [comment]
This may be a useful option to add to `configure()`

**Comment by cdimascio** [comment]
@srnagar this is available in v `5.2.0`

**Comment by srnagar** [comment]
@cdimascio That is great. Thank you! I will give this a try.

**Comment by jongio** [comment]
Very cool. Thanks for doing this.

**Comment by jongio** [comment]
I published a new blog with this update: https://blog.jongallant.com/2020/05/java-dotenv-azure-sdk-update/

**Comment by cdimascio** [comment]
Awesome @jongio! Thanks for sharing.
