### ISSUE TITLE
.env file and Travis

### ISSUE THREAD

**Issue by alakijaayo** [cdimascio/dotenv-kotlin#42]
Afternoon,

Thanks for this, been trying to learn Java and using this file for a project I am building.

Just wanted to ask as I am currently having an issue with regards to Travis-ci and it reading my .env file. I know we shouldn't upload it to Github so have kept the file locally but when my setup goes through Travis before loading to Heroku it gives me the following error message:

io.github.cdimascio.dotenv.DotEnvException: Could not find /.env on the classpath

Would this be a situation where I have to set the classpath somewhere for it to know where to get the environment variables from? Know I have used .env with Node.js and didn't commit the files to GitHub but t knew the variables when the project was launched to Heroku.

Apologies if I sound a bit of a beginner. Thanks

**Comment by cdimascio** [comment]
Hi @alakijaayo, use the `ignoreIfMissing` option when creating the java-dotenv instance to avoid the exception.

```Java
Dotenv dotenv = Dotenv.configure()
        .ignoreIfMissing()
        .load();
```

**Comment by alakijaayo** [comment]
@cdimascio Thanks for your response and apologies for the late reply.

Think it might have worked, but getting a new error:

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spotifyLoginClient' defined in file [/home/travis/build/alakijaayo/SoulRadio/SpotifyAPI/target/classes/server/spotifyAPI/Client/SpotifyLoginClient.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [server.spotifyAPI.Client.SpotifyLoginClient]: Constructor threw exception; nested exception is java.lang.NullPointerException

Think it might be something I am just getting wrong, as it is coming from it failing the test when it tries to get it through on Travis. 

Will keep working on it, but thanks ever so much for your help

**Comment by paulschwarz** [comment]
@alakijaayo since you're using spring, you might be interested to use this https://github.com/paulschwarz/spring-dotenv which is a very adapter for the java-dotenv library. 

(Credit for the amazing work goes to @cdimascio)

**Comment by alakijaayo** [comment]
@paulschwarz Thanks for recommending. Have tried to use your repo as an alternative to work, but every time I run `mvn clean install` in my terminal, I get the following error:

Could not resolve dependencies for project soulradio:soulradio:jar:0.0.1-SNAPSHOT: Failure to find me.paulschwarz:spring-dotenv:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

Have run this with both the pom type there and not there. I am using maven for my spring-boot application. Do I need to add this dependency?

**Comment by cdimascio** [comment]
closing this out. thanks for the issue @alakijaayo
