### ISSUE TITLE
Getting an error when running a jar that uses dotenv

### ISSUE THREAD

**Issue by TheIdanLapid** [cdimascio/dotenv-kotlin#43]
Error: Could not find or load main class io.cdimascio.DotenvKt

It happens when I try to run the jar from a docker container. I guess the docker doesn't find the java classpath for Dotenv.

I use gradle - so in the dependencies I have: `compile 'io.github.cdimascio:java-dotenv:5.2.1'`

Any ideas what to do? Do I need the actual Dotenv.kt file in my project?

@cdimascio

**Comment by cdimascio** [comment]
This sounds like an issue with the jar itself itself or your classpath. Make sure dotenv is added as a dependency and included on the classpath. You might also consider creating a "fat" jar to ensure all of your dependencies including dotenv are present.
