### ISSUE TITLE
How does this work with compiled jars?

### ISSUE THREAD

**Issue by nitrocode** [cdimascio/dotenv-kotlin#5]
Cool project! I'd like to try it and I just had a couple questions.

When the jar file is compiled, are the env vars compiled with it? is there a way to do that? or should the `.env` file reside next to the jar file for it to be read?

**Comment by cdimascio** [comment]
@nitrocode You can do it either way. The code looks for the `.env` file on the filesystem and on the classpath. If you want to build `.env` into jar, be sure `.env` appears somewhere on the classpath.

Here is a simple example of how to arrange your project to include `.env` in the jar. Note, this example,  uses the Maven project structure which is commonplace for Java. With the Maven structure, you can place `.env` in the `resources` directory. See the example --> https://github.com/cdimascio/java-dotenv-example

Also, quick note about the env vars. The vars in the actual environment always take precedence, hence, whether or not you choose to ship the `.env` file, you can always control those variables via the host system's environment.

hope this helps

**Comment by cdimascio** [comment]
@nitrocode im going to close this out. please reopen if you are still having issues
