### ISSUE TITLE
Need example integrating java-dotenv with SpringBoot 2.x

### ISSUE THREAD

**Issue by lospejos** [cdimascio/dotenv-kotlin#6]
If somebody has an example integrating java-dotenv with SpringBoot 2.x, please share code snippet. Thanks

**Comment by cdimascio** [comment]
@lospejos I have an example using spring boot 2 with Kotlin and webflux functional. Hope it proves useful.
Repo: https://github.com/cdimascio/kotlin-swagger-spring-functional-template

Including dotenv as a global: https://github.com/cdimascio/kotlin-swagger-spring-functional-template/blob/master/src/main/kotlin/functional/Env.kt

You could instead use it as a bean, instead of a global
Let me know if this helps

**Comment by cdimascio** [comment]
Closing this out. @lospejos please reopen if you need something beyond what the  examples above provide

**Comment by tobiasbueschel** [comment]
Hi @cdimascio, thanks for your work on this project 👍 

How can I use `java-dotenv` with a Spring project that uses an `application.properties` or `application.yml` file to configure server port, log level etc.?
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

In such an `application.yml`, one can access environment variable using:
```yml
server:
  port: ${SERVER_PORT}
```

But this wouldn't find an environment variable if it's loaded locally using `.env`. One would need to run `System.setProperty` in the main method - are there other, perhaps cleaner ways to achieve the same?

```kotlin
System.setProperty("server.port", dotenv["SERVER_PORT"].toString())
```

**Comment by cdimascio** [comment]
Hmm, I think this may be a good opportunity to create a new Spring specific library that wraps `java-dotenv` to do something similar to what you described above.

It's likely not appropriate to bloat java-dotenv with framework specific logic, however I can certainly see significant value as a Spring user

**Comment by n3v3rf411** [comment]
I use the following (kotlin):
```kotlin
fun main(args: Array<String>) {
	val dotenv = dotenv().entries().associateByTo(hashMapOf(), {it.key}, {it.value}).toMap()

	SpringApplicationBuilder(ApiApplication::class.java)
		.environment(object : StandardEnvironment() {
			override fun customizePropertySources(propertySources: MutablePropertySources) {
				super.customizePropertySources(propertySources)
				propertySources.addLast(MapPropertySource("dotenvProperties", dotenv))
			}
		})
		.run(*args)
}
```

This will add the dotenv entries as a property source succeeding system and environment properties.

**Comment by MichaelSp** [comment]
Here is the same for java

```java
    public static void main(String[] args) {
        Map<String, Object> env = Dotenv.load()
                .entries()
                .stream()
                .collect(
                        Collectors.toMap(DotenvEntry::getKey, DotenvEntry::getValue));
        new SpringApplicationBuilder(Application.class)
                .environment(new StandardEnvironment() {
                    @Override
                    protected void customizePropertySources(MutablePropertySources propertySources) {
                        super.customizePropertySources(propertySources);
                        propertySources.addLast(new MapPropertySource("dotenvProperties", env));
                    }
                }).run(args);
    }
```

**Comment by cdimascio** [comment]
@MichaelSp and @n3v3rf411  thanks so much for these examples.

If either of you is up to it, It would be fantastic to create a PR that makes these code snippets more accessible. Perhaps, create an `examples` folder at the root of this project, add these code snippets there, and provide a link to each from the examples section of the README.

**Comment by MichaelSp** [comment]
I'd still prefer what you [suggested](https://github.com/cdimascio/java-dotenv/issues/6#issuecomment-470596476). If I now created an PR with that, how would that contribute to the delay of your suggested solution? 😁

**Comment by paulschwarz** [comment]
Please may I invite you to review https://github.com/paulschwarz/spring-dotenv which I believe addresses the need for a library as stated here https://github.com/cdimascio/java-dotenv/issues/6#issuecomment-470596476

@cdimascio I'd appreciate your input on this.

**Comment by ptrckdev** [comment]
Thanks for the Java Code, very helpful.

Now I've got the problem that those variables are not getting used for my tests.
Not sure if my issue is getting my database credentials to the Test Class or having to change my Test Class to not use a complete spring server as those tests don't even need a DB connection 🤔

**Comment by freshprinze** [comment]
> Thanks for the Java Code, very helpful.
> 
> Now I've got the problem that those variables are not getting used for my tests.
> Not sure if my issue is getting my database credentials to the Test Class or having to change my Test Class to not use a complete spring server as those tests don't even need a DB connection

Having the same issue. I am thinking of using https://github.com/paulschwarz/spring-dotenv, by @paulschwarz as a fix. I will update how it works out.

**Comment by freshprinze** [comment]
> Please may I invite you to review https://github.com/paulschwarz/spring-dotenv which I believe addresses the need for a library as stated here [#6 (comment)](https://github.com/cdimascio/java-dotenv/issues/6#issuecomment-470596476)
> 
> @cdimascio I'd appreciate your input on this.

This is a nice wrapper. I am hoping to integrate it in a project I am working on. Thank You.

**Comment by sturufous** [comment]
Can I use spring-dotenv in a Java Spring Application that does not use Spring Boot? I have dotenv-java working fine, but spring-dotenv appears to do nothing.

**Comment by paulschwarz** [comment]
@sturufous probably best to move this conversation to https://github.com/paulschwarz/spring-dotenv

In short, this is the hook that registers the property source https://github.com/paulschwarz/spring-dotenv/blob/master/library/src/main/resources/META-INF/spring.factories
