### ISSUE TITLE
Android Could not find /asset/env on the classpath

### ISSUE THREAD

**Issue by JackDPro** [cdimascio/dotenv-kotlin#63]
I found a bug which is the `directory` method that crops one char of the path.

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/1720338/156186417-4a75c24d-b0cb-4073-850f-d483d986adc4.png">

When i set the directory is `/assetss` , it can work well .

**Comment by saikumar1607** [comment]
Try this, it should work
```kt
Dotenv.configure().directory("./assets").filename("env").load();
```

instead of `"/assets"` put `"./assets"`
