### ISSUE TITLE
Latest build on maven

### ISSUE THREAD

**Issue by congnguyen91** [cdimascio/dotenv-kotlin#66]
Hi @cdimascio  The latest release is not available on Maven url. Latest release is 6.3.1 but on the maven is 6.2.2. Thanks.
[https://mavenlibs.com/maven/dependency/io.github.cdimascio](https://mavenlibs.com/maven/dependency/io.github.cdimascio)

<img width="640" alt="Screen Shot 2022-06-07 at 10 55 11" src="https://user-images.githubusercontent.com/18322684/172292730-1cef5849-2579-498c-bba4-0110a43439bd.png">

**Comment by jdvr** [comment]
Hello @congnguyen91, latest build [is available on maven central](https://search.maven.org/artifact/io.github.cdimascio/dotenv-kotlin/6.3.1/jar) and [I am using it on one of my projects.](https://github.com/jdvr/electric-vehicle-charge/blob/main/build.gradle.kts#L43)
