### ISSUE TITLE
Getting environment variables inside docker container

### ISSUE THREAD

**Issue by junaidrazzaq323** [cdimascio/dotenv-kotlin#7]
How to get environment variables inside docker container?
**Use Case:**

Lets say I want to pass environment variables to my docker container but I don't want to make `.env` file part of the docker image. I would set environment variables in docker's yaml file and they will be available to the application running inside the container through `System.getenv()`. However In my case `dotenv.load()` would throw exception that `/.env file is not on classpath`. However dotenv does gets environment variables from system but in the scenario where `.env` isn't part of the container then it would fail throwing the exception.

**Comment by cdimascio** [comment]
@junaidrazzaq323 you want to use the `ignoreIfMissing()` option. This will not throw if `.env` is missing


```java
Dotenv dotenv = Dotenv.configure()
        .directory("./some/path")
        .ignoreIfMalformed()
        .ignoreIfMissing() // <----- use this option
        .load();
```

**Comment by cdimascio** [comment]
@junaidrazzaq323, i hope this answers you're question. closing this out for now
